/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int o = 0;
	char str[60] = "";
	char str1[100] = "";
	//int delay = 1;
	SystemInit();
	EEPROM_Init();
	UartInit(BAUD_9600);
	while(1){

		UartPuts("\r\n");
		UartPuts("-------------------------------------\r\n");
		UartPuts("Enter 1 to write a string into EEPROM\r\n");
		UartPuts("Enter 2 to Read a string from EEPROM\r\n");
		UartPuts("Enter choice :\r\n");
		UartGets(str);
		//UartPuts(str);	DelayMs(30);
		o = 1;

		if(str[0] == '1')
		{
			UartPuts("Enter String :\r\n");
			UartGets(str1);
			EEPROM_Write(0x0020, (uint8_t*)str1, 16);
		}
		else if(str[0] == '2')
		{
			UartPuts("Your String is :\r\n");
			EEPROM_Read(0x0020, (uint8_t*)str1, 16);
			UartPuts(str1);
		}
		else
		{
			if(o == 1)
			{
				UartPuts("Enter Valid choice :\r\n");
				o = 0;
			}
		}

		//UartPuts((int*)str);
		//EEPROM_Write(0x0020, (uint8_t*)str, 16);
		//EEPROM_Read(0x0020, (uint8_t*)str, 16);
	}
	return 0;
}







